### ISSUE TITLE
Could you add an image to the readme file?

### ISSUE THREAD

**Issue by ThiagoMowszet** [christopher-francisco/tmux-status.nvim#1]
it would be nice if you could see how the plugin looks like, so that when you see the readme you can see how it works and its visual aspect.
PS: great plug btw ❤

**Comment by christopher-francisco** [comment]
Hi @ThiagoMowszet  - thank you for opening this issue. I did add a video to the README, however I did it using GitHub web editor so maybe I did it wrong...

Could you confirm whether you're able or not to see this the following in the README?

<img width="969" alt="image" src="https://github.com/user-attachments/assets/4e969503-33d5-48c6-b791-4c9bb3e5355f">

**Comment by ThiagoMowszet** [comment]
Yes! now i can see it.
Thanks 🖖 💯
